Repository LikeLion-FE-React-Project04/project-repo, pull requests merged in 2023-03, with the labels that each got.

#46 [PR] 패키지 적용을 위한 merge
  package.json
  src/components/ProductCard/ProductCard.jsx
  src/components/ProductCard/ProductCard.module.scss
Labels: 🔧setting

#47 ✨ [feat] 서브페이지 공통 타이틀 컴포넌트 제작 #2
  src/components/PageTitle/PageTitle.jsx
  src/components/PageTitle/PageTitle.module.scss
Labels: ✨ Feature

#48 [feat] 로그인 FormInput 공통컴포넌트 #3
  src/components/FormInput/FormInput.jsx
  src/components/FormInput/FormInput.module.scss
  src/components/index.js
  src/pages/SignIn/SignIn.jsx
Labels: ✨ Feature

#49 [feat] SignIn.module.scss 파일만 추가 #3
  src/pages/SignIn/SignIn.module.scss
Labels: ✨ Feature

#51 🧑 [QUESTION] 컴포넌트 범용성 높이기 #50
  src/components/FormInput/FormInput.jsx
  src/components/FormInput/FormInput.module.scss
  src/components/PageTitle/PageTitle.jsx
  src/components/PageTitle/PageTitle.module.scss
  src/pages/SignIn/SignIn.jsx
  src/pages/SignIn/SignIn.module.scss
Labels: 🙋‍♀️ Question

#52 [feat] 폼인풋과 버튼 컴포넌트 완성 #3
  src/components/Button/Button.jsx
  src/components/Button/Button.module.scss
  src/components/FormInput/FormInput.jsx
  src/components/FormInput/FormInput.module.scss
  src/components/index.js
  src/pages/SignIn/SignIn.jsx
  src/pages/SignIn/SignIn.module.scss
Labels: ✨ Feature

#53 [feat] 로그인 마크업 및 css 완성 #3
  src/components/Button/Button.jsx
  src/pages/SignIn/SignIn.jsx
  src/pages/SignIn/SignIn.module.scss
Labels: ✨ Feature

#66 🐛 [fix] 버튼 컴포넌트 클릭이벤트가 안되는 문제 해결
  src/components/Button/Button.jsx
  src/pages/SignIn/SignIn.jsx
Labels: 🐞 BugFix

#68 ✨ [feat] 로그인 인증
  src/firebase/app.js
  src/firebase/auth/index.js
  src/firebase/auth/useSignIn.js
  src/hooks/useDocumentTitle.js
  src/pages/SignIn/SignIn.module.scss
Labels: ✨ Feature

#72 [FEATURE] Counter 컴포넌트 개발
  src/components/Counter/Count.jsx
  src/components/Counter/Counter.jsx
  src/components/Counter/Counter.module.scss
  src/components/Counter/CounterBtn.jsx
  src/components/Counter/CounterBtn.module.scss
  src/store/CounterState.js
Labels: ✨ Feature

#73 [FEATURE] Button 컴포넌트 커스텀 기능추가
  src/components/Button/Button.jsx
  src/components/Button/Button.module.scss
  src/store/cartModalState.js
Labels: ✨ Feature

#77 Feat/#10
  src/assets/footer/ic-blog-30.svg
  src/assets/footer/ic-blog.svg
  src/assets/footer/ic-face-book-30.svg
  src/assets/footer/ic-face-book.svg
  src/assets/footer/ic-instagram-30.svg
  src/assets/footer/ic-instagram.svg
  src/assets/footer/ic-naver-post-30.svg
  src/assets/footer/ic-naver-post.svg
  src/assets/footer/ic-youtube-30.svg
  src/assets/footer/ic-youtube.svg
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.scss
  src/pages/Home/Home.jsx
  tsconfig.json
Labels: ✨ Feature

#79 🐛 [fix] categoryButton.jsx 이미지 경로 해결 및 svg 교체#78
  public/assets/header/ic-hamburger.svg
  src/assets/header/ic-hamburger.svg
  src/components/Header/HeaderNav/CategoryButton.jsx
Labels: 🐞 BugFix

#80 [FEATURE] CartModal 컴포넌트 개발
  src/components/CartModal/CartModal.jsx
  src/components/CartModal/CartModal.module.scss
  src/components/CartModal/TotalPrice.jsx
  src/components/CartModal/TotalPrice.module.scss
  src/components/DarkFilter/DarkFilter.jsx
  src/components/DarkFilter/DarkFilter.module.scss
  src/components/ProductCard/ProductCard.jsx
  src/store/darkFilterState.js
  src/utils/saveCartDataToLocalStorage.js
Labels: ✨ Feature

#81 ✨ [feat] 로그인 인증 및 홈 화면 전환
  src/components/Button/Button.module.scss
  src/firebase/auth/index.js
  src/firebase/auth/useAuthState.js
  src/firebase/auth/useSignOut.js
  src/pages/SignIn/SignIn.jsx
  src/pages/SignIn/SignIn.module.scss
Labels: ✨ Feature

#83 [FEATURE] 검색 창 기능 구현 #76
  src/components/Header/@recoil/inputState.js
  src/components/Header/@recoilhooks/inputHook.js
  src/components/Header/HeaderNav/SearchForm.jsx
  src/components/Header/HeaderNav/SearchForm.module.css
  src/components/Header/SearchInput/SearchInput.jsx
Labels: ✨ Feature

#85 🐛 [fix] 로그인 버튼 2번 클릭 해야 페이지 이동하는 이슈 해결 #82
  src/pages/SignIn/SignIn.jsx
Labels: 🐞 BugFix

#86 ⚡️ [refactoring] 메인모달관련해서 여러 파일로 분리하기 #11
  src/pages/Home/Home.jsx
  src/pages/Home/Mainmodal/useGetCookieEvent.js
  src/utils/getCookie.js
  src/utils/index.js
Labels: 🔨 Refactor

#87 ✨ [feat] main페이지 라인배너 구현 #9
  src/pages/Home/Home.jsx
  src/pages/Home/Linebanner/Linebanner.jsx
  src/pages/Home/Linebanner/Linebanner.module.scss
  src/pages/Home/Mainmodal/Mainmodal.module.scss
Labels: ✨ Feature

#90 ✨ [feat] 로그인 페이지 margin-bottom 스타일 추가
  src/pages/SignIn/SignIn.module.scss
Labels: ✨ Feature

#94 input안에 검색텍스트들을 전송하는 코드 수정 #93
  src/components/Header/HeaderNav/SearchForm.jsx
  src/components/Header/SearchInput/SearchInput.jsx
Labels: ✂ Modify

#97 ✨ [feat] 회원가입 로직 구현 #2
  src/firebase/auth/index.js
  src/firebase/auth/useSignUp.js
  src/firebase/firestrore/index.js
  src/firebase/firestrore/useCreateAuthUser.js
  src/pages/SignUp/SignUp.jsx
Labels: ✨ Feature

#100 [FEATURE] 홈 페이지 완성
  src/components/PageTitle/PageTitle.jsx
  src/index.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/Home.module.scss
  src/pages/ProductDetail/ProductDetail.jsx
Labels: ✨ Feature

#105 ✨ [SETTING] 스토리북 사용법 예시 적용 #104
  src/components/StorybookExample/Button.jsx
  src/components/StorybookExample/Button.stories.ts
  src/components/StorybookExample/button.css
Labels: 🔧setting

#106 ✨ [feat] 상품후기, 상품문의에 쓰이는 Badge컴포넌트 #96
  src/components/Badge/Badge.jsx
  src/components/Badge/Badge.module.scss
Labels: ✨ Feature

#107 ✨ [feat] 상품후기, 상품문의 pageTitle 컴포넌트에 추가
  src/components/PageTitle/PageTitle.jsx
  src/components/PageTitle/PageTitle.module.scss
  src/pages/SignIn/SignIn.jsx
  src/pages/SignUp/SignUp.jsx
Labels: ✨ Feature

#109 🎨 [modify] 로그인 상태일 때, Member도 업데이트 되도록 코드 수정 #108
  src/components/Header/Member/Member.jsx
  src/components/Header/Member/MemberList.jsx
Labels: ✂ Modify

#111 🐛 [fix] 첫 랜더링 이후 상품카드 클릭시 , TypeError 이슈 fix#110
  src/components/Header/HeaderNav/useScrollEvent.js
Labels: 🐞 BugFix

#117 🐛 [fix] Module not found: Can't resolve 이슈수정 #116
  src/components/Button/Button.jsx
  src/pages/Cart/Cart.jsx
Labels: 🐞 BugFix

#119 ✨ [feat]MainCarousel
  src/assets/main/ic-pause-button.svg
  src/assets/main/ic-play-button.svg
  src/pages/Home/Carousel/MainCarousel.jsx
  src/pages/Home/Carousel/MainCarousel.module.scss
Labels: ✨ Feature

#121 [FEATURE] 공용 AccordionItem 컴포넌트 개발
  src/components/Accordion/AccordionHandle.jsx
  src/components/Accordion/AccordionHandle.module.scss
  src/components/Accordion/AccordionItem.jsx
  src/components/Accordion/AccordionItem.module.scss
  src/components/Accordion/AccordionPanel.jsx
  src/components/Accordion/AccordionPanel.module.scss
  src/components/Accordion/CartAccordion.jsx
  src/components/Accordion/CartAccordion.module.scss
  src/components/StorybookExample/Button.stories.ts
Labels: 🔧setting

#127 ✨ [feat] 상품후기, 상품문의에 쓰이는 팝업창 공용 컴포넌트 #96
  .eslintrc.cjs
  public/index.html
  src/assets/product-detail/secret-checked-false.svg
  src/assets/product-detail/secret-checked-true.svg
  src/components/ProductDetailPopUp/PlaceholderInquiry/PlaceholderInquiry.jsx
  src/components/ProductDetailPopUp/PlaceholderInquiry/PlaceholderInquiry.module.scss
  src/components/ProductDetailPopUp/PlaceholderReview/PlaceholderReview.jsx
  src/components/ProductDetailPopUp/PlaceholderReview/PlaceholderReview.module.scss
  src/components/ProductDetailPopUp/ProductDetailPopUp.jsx
  src/components/ProductDetailPopUp/ProductDetailPopUp.module.scss
  src/components/ProductDetailPopUp/Secret/Secret.jsx
  src/components/ProductDetailPopUp/Secret/Secret.module.scss
  src/components/index.js
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.module.scss
  src/store/detailModalState.js
  src/styles/_a11y.css
Labels: ✨ Feature

#128 [TEST] 컴포넌트 storybook을 구현
  src/components/CartModal/CartModal.jsx
  src/components/CartModal/CartModal.module.scss
  src/components/CartModal/CartModal.stories.js
  src/components/CartModal/CartModalLayout.jsx
  src/components/CartModal/CartModalLayout.module.scss
  src/components/Counter/Counter.module.scss
  src/components/Counter/Counter.stories.js
  src/components/ProductCard/ProductCard.jsx
  src/components/ProductCard/ProductCard.stories.js
  src/pages/Home/Carousel/ProductsCarousel.jsx
  src/pages/Home/Home.jsx
  src/store/productListState.js
Labels: storybook

#129 Feat/#103
  src/components/Accordion/CartAccordion.jsx
  src/components/Accordion/CartAccordion.module.scss
  src/components/Accordion/CartAccordion.stories.js
  src/components/CartModal/CartModal.jsx
Labels: storybook

#133 💄[style] 보영님의 피드백을 바탕으로 디테일 문의/리뷰 팝업관련 수정 (feat/#96)
  src/components/ProductDetailPopUp/ProductDetailPopUp.module.scss
  src/components/ProductDetailPopUp/ProductDetailPopUpLayout.module.scss
  src/components/ProductDetailPopUp/Secret/Secret.jsx
  src/components/ProductDetailPopUp/Secret/Secret.module.scss
Labels: ✂ Modify

#135 ✨ [feat] 아코디언 컴포넌트를 사용할 수 있게 마크업 및 CSS 하기 (질문을 위한 중간커밋) #96
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/ProductDetail/ProductDetail.module.scss
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.module.scss
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.stories.js
Labels: ✨ Feature, 🙋‍♀️ Question

#137 Feat/#96
  src/components/ProductDetailPopUp/ProductDetailPopUp.jsx
  src/firebase/app.js
  src/firebase/firestore/index.js
  src/firebase/firestore/useCreateAuthUser.js
  src/firebase/firestore/useDetailCollection.js
  src/firebase/firestore/useDetailFireStore.js
  src/pages/SignUp/SignUp.jsx
Labels: 📜 Documentation, ✨ Feature, 🔨 Refactor

#138 🎨 [modify] 레이아웃에 대한 recoil상태추가 및, data array 콘솔로 확인하기 #96
  src/components/ProductDetailPopUp/ProductDetailPopUp.jsx
  src/components/ProductDetailPopUp/ProductDetailPopUpLayout.jsx
  src/firebase/firestore/useDetailCollection.js
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
  src/pages/ProductDetail/ProductInquiry/ProductInquiryHandle/ProductInquiryHandle.jsx
  src/pages/ProductDetail/ProductInquiry/ProductInquiryHandle/ProductInquiryHandle.module.scss
  src/store/detailLayoutState.js
Labels: ✨ Feature, ✂ Modify

#140 Feat/#96
  src/pages/Home/Mainmodal/Mainmodal.module.scss
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
  src/pages/ProductDetail/ProductInquiry/ProductInquiryHandle/ProductInquiryHandle.jsx
Labels: 🐞 BugFix, ✂ Modify

#141 Feat/#96 - 중간커밋
  src/components/ProductDetailPopUp/ProductDetailPopUp.jsx
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
  src/pages/ProductDetail/ProductInquiry/ProductInquiryAccordion/ProductInquiryAccordion.jsx
  src/pages/ProductDetail/ProductInquiry/ProductInquiryAccordion/ProductInquiryAccordion.module.scss
  src/pages/ProductDetail/ProductInquiry/ProductInquiryHandle/ProductInquiryHandle.jsx
  src/pages/ProductDetail/ProductInquiry/ProductInquiryHandle/ProductInquiryHandle.module.scss
Labels: ✨ Feature

#142 [Feat/#96]
  src/components/ProductDetailPopUp/ProductDetailPopUp.jsx
  src/firebase/firestore/useDetailCollection.js
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
Labels: ✨ Feature

#143 ✨ [feat] 리뷰/문의 팝업창 비밀글 상태/로그인 상태 고려해서 구현 #96
  src/components/ProductDetailPopUp/ProductDetailPopUp.jsx
  src/components/ProductDetailPopUp/Secret/Secret.jsx
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.module.scss
  src/pages/ProductDetail/ProductInquiry/ProductInquiryAccordion/ProductInquiryAccordion.jsx
  src/pages/ProductDetail/ProductInquiry/ProductInquiryAccordion/ProductInquiryAccordion.module.scss
Labels: ✨ Feature, ✂ Modify

#144 ✨ [feat] 상품후기 팝업창에서 등록시 후기 리스트 추가 #98
  src/pages/ProductDetail/ProductReview/ProductReviewList/ProductReviewList.jsx
  src/pages/ProductDetail/ProductReview/ProductReviewList/ProductReviewList.module.scss
  src/pages/ProductDetail/ProductReview/ReviewListContainer.jsx
  src/pages/ProductDetail/ProductReview/ReviewTitleContainer.jsx
Labels: ✨ Feature

#145 ✨ [feat] 상품후기 리스트 하드코딩 제거 #98
  src/pages/ProductDetail/ProductReview/ReviewListContainer.jsx
  src/pages/ProductDetail/ProductReview/ReviewListContainer.module.scss
Labels: ✨ Feature

#146 Feat/#120
  .prettierrc.cjs
  package.json
  src/assets/product-list/ic-pagination-next.svg
  src/assets/product-list/ic-pagination-prev.svg
  src/assets/product-list/ic-pagination1.svg
  src/assets/product-list/ic-pagination2.svg
  src/assets/product-list/ic-pagination3.svg
  src/components/Accordion/AccordionHandle.module.scss
  src/components/Header/Member/Member.jsx
  src/index.jsx
  src/pages/ProductList/@recoil/checkState.js
  src/pages/ProductList/@recoil/renderState.js
  src/pages/ProductList/@recoilHook/checkHook.js
  src/pages/ProductList/BrandList.jsx
  src/pages/ProductList/FilterContainer.jsx
  src/pages/ProductList/FilterContainer.module.css
  src/pages/ProductList/FilterList.jsx
  src/pages/ProductList/FilterList.module.css
  src/pages/ProductList/Pagination.jsx
  src/pages/ProductList/Pagination.module.css
  src/pages/ProductList/ProductList.jsx
  src/pages/ProductList/ProductList.module.css
  src/pages/ProductList/RenderFilterLi.jsx
  src/pages/ProductList/RenderFilterLi.module.css
  src/pages/ProductList/SortButton.jsx
  src/pages/ProductList/SortButton.module.css
  src/store/productListState.js
  webpack/plugins/createDotEnvPlugin.js
Labels: ✨ Feature, ✂ Modify

#147 🐛 [fix] checkbox 이미지 수정 및 페이지네이션 페이지당 아이템 갯수 수정
  src/pages/ProductList/@recoil/renderState.js
  src/pages/ProductList/FilterList.module.css
  src/pages/ProductList/RenderFilterLi.module.css
Labels: 🐞 BugFix

#148 🔨 [refactor] 헤더 검색창 위치 및 크기 조정 및 nav 위치 조정
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/components/Header/HeaderNav/HeaderNav.module.css
  src/components/Header/HeaderNav/HeaderNavMenu.module.css
  src/components/Header/SearchInput/SearchInput.module.css
Labels: 🔨 Refactor

#154 ✨ [feat] 상품 후기 리스트 페이지네이션 #98
  src/pages/ProductDetail/ProductReview/@recoil/renderState.js
  src/pages/ProductDetail/ProductReview/ProductReviewList/ProductReviewList.jsx
  src/pages/ProductDetail/ProductReview/ReviewListContainer.jsx
  src/pages/ProductDetail/ProductReview/ReviewListContainer.module.scss
Labels: ✨ Feature

#155 ✨ [feat] 문의 팝업창 페이지네이션 적용 #96
  src/components/DetailPagination/DetailPagination.jsx
  src/components/DetailPagination/DetailPagination.module.css
  src/pages/ProductDetail/ProductInquiry/@recoil/renderState.js
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.module.scss
  src/pages/ProductDetail/ProductInquiry/ProductInquiryAccordion/ProductInquiryAccordion.jsx
Labels: ✨ Feature

#158 ✨ [feat] 상품 후기 리스트 뱃지, 이름 너비 고정 #98
  src/pages/ProductDetail/ProductReview/ProductReviewList/ProductReviewList.jsx
  src/pages/ProductDetail/ProductReview/ProductReviewList/ProductReviewList.module.scss
Labels: ✨ Feature

#159 🎨 [REFACTORIGN ]ProductThumbnail 로직 수정
  src/pages/ProductDetail/ProductThumbnail/ProductThumbnail.jsx
  src/pages/ProductDetail/ProductThumbnail/ProductThumbnail.module.scss
Labels: ✨ Feature, 🔨 Refactor

#160 🐛 [fix] 상품 후기와 상품 문의 페이지네이션이 같이 동작하는 버그 수정 #98
  src/pages/ProductDetail/ProductReview/@recoil/renderState.js
  src/pages/ProductDetail/ProductReview/ProductReviewList/ProductReviewList.jsx
Labels: 🐞 BugFix

#161 ✨ [feat] 상품 후기 리스트 총 개수 #98
  src/pages/ProductDetail/ProductReview/ReviewListContainer.jsx
Labels: ✨ Feature

#162 Feat/#156
  public/index.html
Labels: 🐞 BugFix

#163 🐛 [fix] 상품 후기 리스트 총 개수 못불러오는 버그 해결 #98
  src/pages/ProductDetail/ProductReview/ReviewListContainer.jsx
Labels: 🐞 BugFix

#164 ✨ [feat] 상품 후기 작성 시 제목에 자동으로 상품이름 등록되게 하기 #98
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/ProductDetail/ProductReview/@recoil/renderState.js
  src/pages/ProductDetail/ProductReview/ProductReviewList/ProductReviewList.jsx
  src/pages/ProductDetail/ProductReview/ReviewListContainer.jsx
Labels: ✨ Feature

#167 Feat/#149
  src/pages/ProductList/@recoil/checkState.js
  src/pages/ProductList/@recoil/renderState.js
  src/pages/ProductList/BrandList.jsx
  src/pages/ProductList/FilterList.jsx
  src/pages/ProductList/Pagination.jsx
  src/pages/ProductList/ProductList.jsx
  src/pages/ProductList/RenderFilterLi.jsx
Labels: ✨ Feature, ✂ Modify

#169 ✨ [feat] ProductList- 총 갯수 마크업 및 기능구현 #168
  src/assets/product-list/product-list-banner.png
  src/pages/ProductList/ProductList.jsx
  src/pages/ProductList/ProductList.module.css
Labels: ✨ Feature

#173 ✨ [feat] 상품 후기 리스트 비어있으면 svg출력 #98
  src/assets/product-detail/empty-product-review-list.svg
  src/pages/ProductDetail/ProductReview/ReviewListContainer.jsx
Labels: ✨ Feature

#174 ✨ [feat] 상품 후기 리스트 비어있을 때 svg에 alt 추가 #98
  src/pages/ProductDetail/ProductReview/ReviewListContainer.jsx
Labels: ✨ Feature

#175 Modify/#171
  src/assets/product-list/ic-notFound.svg
  src/assets/product-list/ic-return.svg
  src/pages/ProductList/@recoilHook/useResetRenderAllFilter.js
  src/pages/ProductList/FilterContainer.jsx
  src/pages/ProductList/FilterList.jsx
  src/pages/ProductList/Pagination.jsx
  src/pages/ProductList/ProductList.jsx
  src/pages/ProductList/ProductList.module.css
  src/pages/ProductList/SortButton.jsx
Labels: ✨ Feature, ✂ Modify, 🔨 Refactor

#177 Feat/#156 기능 추가 및 버그 수정
  package.json
  src/pages/Cart/Address/Address.jsx
  src/pages/Cart/Address/Address.module.scss
  src/pages/Cart/Cart.jsx
  src/pages/Cart/Cart.module.scss
  src/pages/Cart/CartAccordion/CartDataCheckBox.jsx
  src/pages/Cart/PaymentPrice/PaymentPrice.jsx
  src/pages/Cart/PaymentPrice/PaymentPrice.module.scss
  src/pages/Cart/PriceInfo/PriceInfo.jsx
  src/pages/Home/Carousel/MainCarousel.jsx
  src/pages/Home/Carousel/ProductsCarousel.jsx
  src/pages/ProductDetail/ProductDetail.jsx
  src/store/addressState.js
Labels: 🐞 BugFix, ✨ Feature

#179 Feat/#96
  src/components/Button/Button.jsx
  src/components/Button/Button.module.scss
  src/components/Footer/Footer.module.scss
  src/components/ProductDetailPopUp/ProductDetailPopUp.jsx
  src/components/ProductDetailPopUp/ProductDetailPopUp.module.scss
  src/firebase/firestore/useDetailCollection.js
  src/pages/ProductDetail/ProductInquiry/@recoil/productId.js
Labels: ✨ Feature, ✂ Modify

#180 Feat/#156 브라우저 헤더 설정 변경
  public/index.html
  webpack/plugins/createHtmlPlugin.js
Labels: ✨ Feature, 🔧setting

#185 🔨 [refactor] ProductList 코드 수정 #183
  src/pages/ProductList/FilterContainer.jsx
  src/pages/ProductList/FilterList.jsx
  src/pages/ProductList/ProductList.jsx
  src/pages/ProductList/SortButton.jsx
Labels: 🔨 Refactor
