Repository LikeLion-FE-React-Project04/project-repo, pull requests merged in 2023-05, with the labels that each got.

#291 Feat/#238
  public/index.html
  src/components/AlertBox/BtnType/ConfirmAndCancel/ConfirmAndCancel.module.scss
  src/pages/Home/LineBanner/LineBanner.jsx
Labels: 🥰 Accessibility, ✂ Modify

#294 Refactoring/#292 캐로셀 웹접근성 수정
  src/components/ProductCard/CartButton.jsx
  src/components/ProductCard/ProductCard.jsx
  src/pages/Home/Carousel/MainCarousel.jsx
  src/pages/Home/Carousel/MainCarousel.module.scss
  src/pages/Home/Carousel/ProductsCarousel.jsx
  src/pages/Home/Carousel/ProductsCarousel.module.scss
  src/pages/Layout/Layout.jsx
  src/pages/Layout/Layout.module.scss
  src/styles/_base.css
Labels: 🐞 BugFix, 🥰 Accessibility, 🔨 Refactor

#295 Feat/#238
  package.json
  src/components/Footer/Footer.jsx
  src/components/Header/HeaderIcon/MainIcon.jsx
  src/components/Header/HeaderLogoContainer/HeaderLogo.jsx
  src/components/Header/HeaderLogoContainer/NewBadge.jsx
  src/components/Header/HeaderNav/CategoryButton.jsx
  src/components/Header/HeaderNav/SearchForm.jsx
  src/components/Header/Member/MemberList.jsx
  src/components/Header/SearchInput/SearchInput.jsx
  src/components/Header/Topbanner/TopbannerCloseButton.jsx
  src/components/ProductDetailPopUp/ProductDetailPopUp.jsx
  src/pages/Cart/Address/Address.jsx
  src/pages/Cart/CartAccordion/CartAccordionHandle.jsx
  src/pages/ProductDetail/DetailInformation/DetailInformation.jsx
  src/pages/ProductDetail/ProductInformation/ProductInformation.jsx
  src/pages/ProductDetail/ProductThumbnail/ProductThumbnail.jsx
  src/pages/ProductList/ProductList.jsx
  src/pages/SignUp/Agreement/Agreement.jsx
Labels: 🥰 Accessibility

#297 Refactoring/#296 장바구니 알림 팝업창 리팩토링
  package.json
  src/components/CartPopup/CartPopup.jsx
  src/components/CartPopup/CartPopup.module.scss
Labels: 🐞 BugFix, 🔨 Refactor

#301 🐛 [fix] 디테일페이지의 네비게이션바 버튼 포커스 스타일 관련 버그 #300
  src/pages/ProductDetail/ProductDetailMenu/ProductDetailMenu.module.scss
Labels: 🐞 BugFix, ✂ Modify

#302 Refactoring 2/#225 네비게이션 수정
  src/pages/ProductDetail/DetailInformation/DetailInformation.jsx
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/ProductDetail/ProductInformation/ProductInformation.jsx
  src/pages/ProductDetail/ProductThumbnail/ProductThumbnail.jsx
  src/pages/SignUp/@hook/useSignUpSubmit.js
Labels: 🐞 BugFix

#306 불필요한 코드 정리
  src/components/ProductDetailPopUp/ProductDetailPopUp.jsx
  src/firebase/firestore/useDetailCollection.js
  src/firebase/firestore/useDetailFireStore.js
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
Labels: 🔨 Refactor

#308 ✨ [feat] useEffect를 사용해서 page를 1로 초기화 시키기 #307
  src/pages/ProductDetail/ProductReview/ReviewListContainer.jsx
Labels: 🐞 BugFix, ✨ Feature
