Repository LikeLion-FE-React-Project04/project-repo, pull requests merged in 2023-04, with the labels that each got.

#190 Feat/#96
  src/components/ScrollToTop/ScrollToTop.js
  src/index.jsx
  src/pages/Layout/Layout.jsx
  src/pages/ProductDetail/ProductDetail.jsx
Labels: 🐞 BugFix, ✨ Feature, ✂ Modify

#193 Feat/#96
  public/index.html
  src/components/TransparentFilter/@recoil/transparentFilterState.js
  src/components/TransparentFilter/TransparentFilter.jsx
  src/components/TransparentFilter/TransparentFilter.module.scss
  src/pages/Home/Home.jsx
  src/pages/Home/Mainmodal/@recoil/MainmodalState.js
  src/pages/Home/Mainmodal/Mainmodal.jsx
  src/pages/Home/Mainmodal/Mainmodal.module.scss
  src/pages/Home/Mainmodal/Mainmodal.stories.js
  src/pages/Home/Mainmodal/MainmodalLayout.jsx
  src/pages/Home/Mainmodal/MainmodalLayout.module.scss
  src/pages/Home/Mainmodal/useGetCookieEvent.js
  src/pages/Layout/Layout.jsx
Labels: 🐞 BugFix, ✨ Feature, ✂ Modify

#195 Feat/#96
  src/components/TransparentFilter/@recoil/transparentFilterState.js
  src/pages/Home/Home.jsx
  src/pages/Home/Mainmodal/useGetCookieEvent.js
Labels: 🐞 BugFix, ✂ Modify

#196 Feat/#96
  src/components/ProductDetailPopUp/ProductDetailPopUp.jsx
Labels: ✨ Feature, ✂ Modify, 🔨 Refactor

#197 Modify/#191
  .gitignore
  src/pages/ProductList/@recoil/checkState.js
  src/pages/ProductList/@recoil/renderState.js
  src/pages/ProductList/BrandButtons.jsx
  src/pages/ProductList/BrandButtons.module.css
  src/pages/ProductList/BrandList.jsx
  src/pages/ProductList/BrandList.module.css
  src/pages/ProductList/FilterList.jsx
  src/pages/ProductList/ProductList.jsx
  src/pages/ProductList/RenderFilterLi.jsx
Labels: ✂ Modify, 🔨 Refactor

#199 ✨ [feat] 필터 영역 스크롤 기능 추가 및 바 숨기기 #198
  src/pages/ProductList/FilterList.module.css
Labels: ✨ Feature

#201 ✨ [feat] 각 페이지의 상품에 맞는 explanation 제공하기 #200
  src/pages/ProductDetail/ProductThumbnail/ProductThumbnail.jsx
  src/store/productListState.js
Labels: ✨ Feature, ✂ Modify

#205 ✨ [feat] 문의/후기글의 작성자 이름일부를 *로 가리기 #204
  src/firebase/firestore/useDetailCollection.js
  src/utils/getStarName.js
Labels: ✨ Feature

#211 Feat/#96
  src/components/ProductDetailPopUp/ProductDetailPopUp.jsx
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.module.scss
  src/pages/ProductDetail/ProductInquiry/ProductInquiryAccordion/ProductInquiryAccordion.jsx
  src/pages/ProductDetail/ProductInquiry/ProductInquiryAccordion/ProductInquiryAccordion.module.scss
  src/pages/ProductDetail/ProductReview/ReviewTitleContainer.module.scss
Labels: ✂ Modify

#213 [FEATURE] 장바구니 알림 팝업 모달 구현
  .eslintrc.cjs
  src/components/CartModal/CartModal.jsx
  src/components/CartPopup/CartPopup.jsx
  src/components/CartPopup/CartPopup.module.scss
  src/pages/Layout/Layout.jsx
  src/store/Popup.js
Labels: ✨ Feature

#214 Feat/#212
  src/pages/Home/Mainmodal/Mainmodal.jsx
  src/pages/Home/Mainmodal/Mainmodal.module.scss
Labels: 🥰 Accessibility, ✨ Feature, ✂ Modify

#216 Feat/#212
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.module.scss
  src/pages/ProductDetail/ProductReview/ReviewListContainer.jsx
  src/pages/ProductDetail/ProductReview/ReviewListContainer.module.scss
Labels: ✨ Feature, ✂ Modify

#217 🐛 [fix] 한페이지또는 데이터가 없을때도 고려 #207
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
  src/pages/ProductDetail/ProductReview/ReviewListContainer.jsx
Labels: 🐞 BugFix, ✨ Feature

#218 💄 [style] 버튼 스타일 수정 #207
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.module.scss
  src/pages/ProductDetail/ProductReview/ReviewListContainer.module.scss
Labels: ✂ Modify

#219 🐛 [fix] 별이름 로직을 구현하다가 생긴 버그 해결 #204
  src/firebase/firestore/useDetailCollection.js
  src/pages/ProductDetail/ProductInquiry/ProductInquiryAccordion/ProductInquiryAccordion.jsx
  src/pages/ProductDetail/ProductReview/ProductReviewList/ProductReviewList.jsx
Labels: 🐞 BugFix

#222 🐛 [BUGFIX] 컨벤션에 맞게 파일이름 수정 #221
  src/components/DetailPagination/DetailPagination.module.css
  src/pages/ProductList/Pagination.module.css
Labels: 🐞 BugFix

#227 Feat/#212
  src/components/TransparentFilter/@recoil/transparentFilterState.js
  src/components/TransparentFilter/TransparentFilter.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/Mainmodal/@recoil/MainmodalState.js
  src/pages/Home/Mainmodal/Mainmodal.jsx
  src/pages/Home/Mainmodal/Mainmodal.module.scss
  src/pages/Home/Mainmodal/Mainmodal.stories.js
  src/pages/Home/Mainmodal/MainmodalLayout.jsx
  src/pages/Home/Mainmodal/MainmodalLayout.module.scss
  src/pages/Home/Mainmodal/useGetCookieEvent.js
Labels: 🐞 BugFix, 🥰 Accessibility, ✨ Feature, ✂ Modify

#229 Feat/#212
  public/index.html
  src/components/AlertBox/@recoil/alertModalState.js
  src/components/AlertBox/AlertBox.jsx
  src/components/AlertBox/AlertBox.module.scss
  src/components/AlertBox/AlertBoxLayout.jsx
  src/components/AlertBox/AlertBoxLayout.module.scss
  src/components/AlertBox/BtnType/ConfirmAndCancel/ConfirmAndCancel.jsx
  src/components/AlertBox/BtnType/ConfirmAndCancel/ConfirmAndCancel.module.scss
  src/components/AlertBox/BtnType/OnlyConfirm/OnlyConfirm.jsx
  src/components/AlertBox/BtnType/OnlyConfirm/OnlyConfirm.module.scss
  src/components/ProductDetailPopUp/ProductDetailPopUp.jsx
  src/components/ProductDetailPopUp/ProductDetailPopUp.module.scss
  src/components/ProductDetailPopUp/Secret/Secret.jsx
  src/components/ProductDetailPopUp/Secret/Secret.module.scss
  src/pages/Layout/Layout.jsx
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
  src/pages/ProductDetail/ProductReview/ReviewTitleContainer.jsx
Labels: 🐞 BugFix, 🥰 Accessibility, ✨ Feature, ✂ Modify

#230 ✨ [feat] 비밀글로 설정하기에 포커스 가능하게 하기 #228
  src/components/ProductDetailPopUp/Secret/Secret.module.scss
Labels: 🥰 Accessibility

#231 🎨 [modify] MainModal 파일명 변경 #212
  src/pages/Home/Mainmodal/MainModal.jsx
  src/pages/Home/Mainmodal/MainModal.module.scss
  src/pages/Home/Mainmodal/MainModal.stories.js
  src/pages/Home/Mainmodal/MainModalLayout.jsx
  src/pages/Home/Mainmodal/MainModalLayout.module.scss
Labels: ✂ Modify

#233 🐛 [fix] MainModal로 이름 변경 위해 캐시 비우기 #212
  src/pages/Home/MainModal/@recoil/MainModalState.js
  src/pages/Home/MainModal/MainModal.jsx
  src/pages/Home/MainModal/MainModal.module.scss
  src/pages/Home/MainModal/MainModal.stories.js
  src/pages/Home/MainModal/MainModalLayout.jsx
  src/pages/Home/MainModal/MainModalLayout.module.scss
  src/pages/Home/MainModal/useGetCookieEvent.js
Labels: 🐞 BugFix

#234 Feat/#212
  src/components/AlertBox/@recoil/alertModalState.js
  src/components/AlertBox/AlertBox.jsx
  src/pages/Cart/CartAccordion/CartAccordionPanelItem.jsx
  src/pages/Home/MainModal/@recoil/MainModalState.js
  src/pages/Home/MainModal/MainModal.jsx
  src/pages/Home/MainModal/useGetCookieEvent.js
Labels: 🐞 BugFix, ✨ Feature

#239 🎨 [modify] 웹 접근성 피드백을 고려해서 수정하기 #238
  src/components/Footer/Footer.jsx
Labels: 🥰 Accessibility

#240 Feat/#238
  src/pages/ProductDetail/ProductInquiry/ProductInquiryAccordion/ProductInquiryAccordion.jsx
Labels: ✨ Feature, ✂ Modify

#241 ⚡️ [refactoring] Header - 웹 접근성 피드백 내용 수정 #236
  src/components/Header/HeaderIcon/HeaderIcon.jsx
  src/components/Header/HeaderLogoContainer/HeaderLogo.jsx
  src/components/Header/HeaderLogoContainer/NewBadge.jsx
  src/components/Header/HeaderNav/CategoryButton.jsx
  src/components/Header/HeaderNav/MainIconList.jsx
  src/components/Header/HeaderNav/SearchForm.jsx
  src/components/Header/Member/MemberList.jsx
  src/components/Header/SearchInput/SearchInput.jsx
  src/components/Header/Topbanner/Topbanner.jsx
Labels: 🥰 Accessibility, 🔨 Refactor

#247 Feat/#238
  src/components/AlertBox/@recoil/alertModalState.js
  src/components/AlertBox/customHooks/useAlertBox.js
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
  src/pages/ProductDetail/ProductReview/ReviewTitleContainer.jsx
Labels: ✨ Feature, ✂ Modify, 🔨 Refactor

#250 🎨 [REFACTORING] 회원가입 경고 모달 커스텀 훅 적용 #220
  src/pages/SignUp/@hook/useConfirmEmail.js
  src/pages/SignUp/@hook/useSignUpSubmit.js
Labels: ✂ Modify

#251 🎨 [modify] 경로변경 및 성능최적화를 고려해서 useMemo적용 #220
  src/components/AlertBox/@hook/useAlertBox.js
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
  src/pages/ProductDetail/ProductReview/ReviewTitleContainer.jsx
Labels: ✂ Modify, 🔨 Refactor

#252 🎨 [MODIFY] alertbox 사용 조건에 맞게 코드 수정
  src/pages/Cart/CartAccordion/CartAccordionPanelItem.jsx
  src/pages/SignUp/@hook/useConfirmEmail.js
  src/pages/SignUp/@hook/useSignUpSubmit.js
Labels: ✂ Modify, 🔨 Refactor

#254 [BUGFIX] 회원가입 버그 수정
  src/hooks/useAddress.jsx
  src/pages/Cart/Address/Address.jsx
  src/pages/SignUp/@hook/useSignUpValidation.js
  src/pages/SignUp/SignUpAddress/SignUpAddress.jsx
  src/utils/checkValidation.js
Labels: 🐞 BugFix

#255 [BUGFIX] 비밀번호 확인 버그 수정
  src/pages/SignUp/@hook/useSignUpSubmit.js
  src/pages/SignUp/@hook/useSignUpValidation.js
  src/pages/SignUp/SignUp.jsx
  src/utils/checkValidation.js
Labels: 🐞 BugFix

#256 Feat/#248 회원가입 유효성 문구 수정
  src/utils/checkValidation.js
Labels: ✂ Modify

#257 🎨 [modify] Linebanner -> Hello 중간이름으로 바꾸기 #9
  src/pages/Home/Hello/Hello.jsx
  src/pages/Home/Hello/Hello.module.scss
Labels: ✂ Modify

#258 🎨 [modify] Hello -> LineBanner 중간이름에서 원하는 이름으로 바꾸기 #9
  src/pages/Home/Home.jsx
  src/pages/Home/LineBanner/LineBanner.jsx
  src/pages/Home/LineBanner/LineBanner.module.scss
Labels: ✂ Modify

#260 💄 [style] 비활성화/활성화 상태일 때 cursor모양 다르게 하기 #243
  src/components/Counter/CounterBtn.module.scss
Labels: ✂ Modify

#261 Refactoring/#225
  src/pages/ProductDetail/@hook/useMoveScroll.js
  src/pages/ProductDetail/DetailInformation/DetailInformation.jsx
  src/pages/ProductDetail/DetailInformation/DetailInformation.module.scss
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/ProductDetail/ProductDetail.module.scss
  src/pages/ProductDetail/ProductDetailMenu/ProductDetailMenu.jsx
  src/pages/ProductDetail/ProductInformation/ProductInformation.jsx
  src/pages/ProductDetail/ProductInformation/ProductInformation.module.scss
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
  src/pages/ProductDetail/ProductThumbnail/ProductThumbnail.jsx
  src/pages/ProductDetail/ProductThumbnail/ProductThumbnail.module.scss
Labels: ✨ Feature, ✂ Modify

#263 ✨ [feat] 네비게이션바의 후기탭에 현재 후기의 개수가 업데이트 #225
  src/pages/ProductDetail/ProductDetail.jsx
Labels: ✨ Feature

#264 🐛 [fix] 코드 충돌로 인한 오류 해결 #225
  src/pages/ProductDetail/ProductDetail.jsx
Labels: 🐞 BugFix

#265 ✨ [feat] 스크롤 내릴 시 헤더 아래로 위치 고정 #225
  src/pages/ProductDetail/ProductDetailMenu/ProductDetailMenu.module.scss
Labels: ✨ Feature

#267 Feat/#248 회원가입 문구 수정
  src/utils/checkValidation.js
Labels: 🐞 BugFix

#270 ✨ [feat] 스크롤 이동에 따른 버튼 스타일 변화 #225
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/ProductDetail/ProductDetailMenu/ProductDetailMenu.jsx
  src/pages/ProductDetail/ProductDetailMenu/ProductDetailMenu.module.scss
  src/pages/ProductDetail/ProductInquiry/ProductInquiry.module.scss
  src/pages/ProductDetail/ProductReview/ProductReview.module.scss
Labels: ✨ Feature, ✂ Modify

#271 🎨 [REFACTORING] 네비게이션 스크롤 이벤트 리팩토링 #225
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/ProductDetail/ProductDetailMenu/ProductDetailMenu.jsx
Labels: 🐞 BugFix, 🔨 Refactor

#272 Feat/#238
  src/pages/ProductDetail/ProductDetailMenu/ProductDetailMenu.jsx
  src/pages/ProductDetail/ProductDetailMenu/ProductDetailMenu.module.scss
Labels: ✂ Modify

#273 🎨 [modify] setPosition설정 범위 변화 #225
  src/pages/ProductDetail/ProductDetail.jsx
Labels: ✂ Modify

#276 Feat/#238
  public/assets/favicon/favicon.png
  public/assets/open-graph/open-graph-karly.png
  public/index.html
  src/pages/Cart/Cart.jsx
  src/pages/Home/Home.jsx
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/ProductList/ProductList.jsx
  src/pages/SignIn/SignIn.jsx
  src/pages/SignUp/SignUp.jsx
  webpack/plugins/createHtmlPlugin.js
Labels: ✨ Feature

#277 🐛 [BUGFIX] 스크롤 이벤트 버그 해결 #225
  src/pages/ProductDetail/ProductDetail.jsx
Labels: 🐞 BugFix

#279 🐛 [fix] 팝업창 ProductDetailPopUpLayout.module.scss에서, bottom과 right 삭제 #96
  src/components/ProductDetailPopUp/ProductDetailPopUpLayout.module.scss
Labels: ✂ Modify

#282 🐛 [BUGFIX] 탭접근성 버그 수정 #206
  src/components/CartModal/CartModal.jsx
Labels: 🐞 BugFix

#285 🐛 [BUGFIX] 장바구니 알림 팝업 위치 버그 수정 #210
  src/components/CartPopup/CartPopup.jsx
  src/components/CartPopup/CartPopup.module.scss
  src/components/Header/HeaderIcon/HeaderIcon.jsx
  src/components/Header/HeaderNav/MainIconList.jsx
  src/pages/Layout/Layout.jsx
Labels: 🐞 BugFix

#287 🎨 [modify] 외부링크 svg파일들에 title태그 추가하기 #238
  src/assets/footer/ic-blog-30.svg
  src/assets/footer/ic-face-book-30.svg
  src/assets/footer/ic-instagram-30.svg
  src/assets/footer/ic-naver-post-30.svg
  src/assets/footer/ic-youtube-30.svg
  src/components/Footer/Footer.jsx
Labels: 🥰 Accessibility, ✂ Modify

#288 🎨 [modify] 외부링크 svg파일들에 title태그 추가하기 #238
  src/assets/footer/ic-blog-30.svg
  src/assets/footer/ic-face-book-30.svg
  src/assets/footer/ic-instagram-30.svg
  src/assets/footer/ic-naver-post-30.svg
  src/assets/footer/ic-youtube-30.svg
  src/components/Footer/Footer.jsx
Labels: 🥰 Accessibility, ✂ Modify
